<?php 


\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à eau + kit de courroie de distribution","prix1"=>63050,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Kit de courroies d'accessoires","prix1"=>53300,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Kit de distribution","prix1"=>43350,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Courroie trapézoide à nervures (d'accessoires)","prix1"=>6500,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Poulie Damper","prix1"=>73450,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Huile moteur","prix1"=>37700,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Joint de bouchon vidange","prix1"=>650,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bouchon vidange","prix1"=>16900,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Injecteur","prix1"=>363350,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Porte-injecteur + injecteur (complet)","prix1"=>104650,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à carburant","prix1"=>96200,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Debitmètre de masse d'air","prix1"=>63050,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Electrovanne","prix1"=>31200,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bougie d'allumage","prix1"=>615,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bobine d'allumage","prix1"=>13650,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Jeu de fils d'allumage","prix1"=>21450,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Tête d'allumeur","prix1"=>6500,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Doigt allumeur","prix1"=>4550,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Joint de culasse","prix1"=>20800,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Joint  de cache culbuteurs","prix1"=>11700,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pochette de joint moteur","prix1"=>29900,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bague d'étanchiété, vilebrequin","prix1"=>650,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Vis de culasse","prix1"=>650,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bougie de préchauffage","prix1"=>7150,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Relais, Boîtier de préchauffage","prix1"=>55250,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, régime","prix1"=>33150,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, position d'arbre à cames","prix1"=>12350,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, pression du tuyau  d'admission","prix1"=>41600,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, pression de carburant","prix1"=>38350,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, pression d'huile","prix1"=>18850,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Turbo auto","prix1"=>473200,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Capteur, pression de suralimentation","prix1"=>36440,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Gaine de suralimentaion","prix1"=>18200,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Kit de montage, compresseur","prix1"=>16900,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à eau","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à haute pression","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe d'injection","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à eau additionnelle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Support moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Support, suuspension du moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Butée élastique, suspension du moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Support de palier, suspension du moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Pompe à huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Jauge de niveau d'huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Joint de carter d'huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Carter d'huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Bouchon, goulotte de remplissage d'huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Soupape d'admission","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Soupape d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Joint de queue de soupape","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Poussoir hydraulique","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Culbuteur, distribution","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Moteur Huile","produit"=>"Réservoir de carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Phare","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Feu arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Feu antibrouillard","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Feuu clignotant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Interrupteur, feu-marche arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Balai d'essuie-glace","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Moteur d'essuie-glace","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Pompe d'eau de nettoyage, nettoyage des vitres","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Bras d'essuie-glace, nettoyage des vitres","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Liquides lave-glace","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Ampoule de phare","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Ampoule, feu  stop/feu arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Ampoule, feu de stationnement/de position","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Ampoule, feu clignotant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Ampoule, feu longue portée","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Rétroviseur extérieur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Verre de rétroviseur, rétroviseur extérieur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Revêtement, rétroviseur extérieur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Pompe d'eau de nettoyage, nettoyage des phares","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Système de nettoyyage des phares","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Visibilité","produit"=>"Bras d'essuie-glace, nettoyage des phares","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Jeu de 2 amortisseurs avant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Jeu de 2 amortisseurs arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Amortisseur à l'unité","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Ressort de suspension unitaire","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Trianngle ou bras de suspennsion","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Silent bloc de suspension","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Jeu de bras, suspension de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Suspension, corps de l'essieu","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Suspennsion, support d'essieu","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Rotule de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Biellette de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Rotule de direction intérieure","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Joint-soufflet, direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Barre de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Roulement de roue ","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Moyeu de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Roulement de roue ","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Circlip","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Bague d'étanchiété, roulement de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Cardan","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Soufflet de cardans","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Bague d'étanchéité, différentiel","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Joint, arbre longitudinal","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Joint-soufflet, arbre de commande","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Biellette de barre stabilisatrice","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Rotule de suspension","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Vis de serrage, Suspension articulée/route de suspension","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Crémaillère de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Pompe de direction assistée","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Soufflets de diirection","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Colonne de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Jeu de joints-soufflets, direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Butée simple de jambe élastique","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Butée élastique, suspension du moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Aneeau, palier-support jambe de suspension","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Joint, butée simple de jambe élastique","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Kit de réparation, suspension su stabilisateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Kit de réparation suspension de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Bride de ressort","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Coussinet de palier, reesoort à larmes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Jumelle de ressort","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Support, support de ressort","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Suspension, ressort à larmes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Suspension, stabilisateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Coussinet de palier, stabilisateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Fusée d'essieu, suspension de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Joint Homocinétiques","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Croisillon, satellite-différentiel","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Accumulateur de , suspension/amortissement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Direction - Suspension - Train","produit"=>"Ressort pneumatique, Châssis","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Plaquette de frein avant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Plaquettes de frein arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Contacteur d'usure de plaquettes de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Kit d'accessoires, plaquette de frein à disque","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Jeu de 2 disques de frein avant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Jeu de 2 disques de frein arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Vis, disque de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Kit de freins, frein à disques","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Etrier de frein neuf","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Etrier de frein échange standard","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Kit de réparation, étrier  de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Flexible de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Liquide de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Maître-cylindre de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Accumulateur de pression, freinage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Cylindre de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Jeu de 4 mâchoires de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Mâchoire de frein parking","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Kit d'accessoires, mâchoires de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Jeu de mâchoires de frein avec ressorts","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Jeu de 2 tambours de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Capteur ABS","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Cable de frein à main","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Interrupteur des feux de freins","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Anneau de palpeur,ABS","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Servo-frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Pompe à vide, système de freinage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Freinage","produit"=>"Joint, pompe à vide","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Filtre à huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Filtre à carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Filtre à air","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Filtre, air de l'habitacle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Filtre hydraulique, direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Joint d'étanchéité, boitier de filtre à huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Boitier, filtre de carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Couvercle, boitier du filtre d'huile","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Filtration","produit"=>"Kit de filtres hydrauliques, transmission automatique","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Batterie voiture","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Condensateur d'antiparasitage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Alternateur neuf","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Alternateur échange standard","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Poulie roue libre, alternateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Régulateur d'alternateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Poulie, alternateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Balais, alternateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Démarreur neuf","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Démarreur échange standard","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Balais, démarreur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Interrupteur d'allumagge de démarreur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Contacteur, démarreur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Kit de réparration; démarreur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Démarrage et Charge","produit"=>"Générateur démarreur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Kit d'embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Kit d'embrayage avec volant moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Volant moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Emetteur, embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Récepteur, embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Suspension, boite de vitesse manuelle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Boite d'étanchéité, boite de vitesse manuelle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Cable de commande de boite de vitesse","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Kit de réparation, levier de changement de vitesse","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Triangle de sélection/de changement de vitesses","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Cable d'embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Douillie de guidage, embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Embrayage et boite de vitessee","produit"=>"Commande, embrayage GRA","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Vanne EGR","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Sonde Lambda","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Capteur de température de gaz d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Transmetteur de pression, contrôle des gaz d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Radiateur, réaspiration des gaz d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Silencieux arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Tuyau d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Silencieux central","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Silencieux avant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Echappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Catalyseur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Filtre à particules/à suie, FAP","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Conduire à press, capteur de press","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Précatalyseur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Silentbloc de suspension","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Joint d'étanchéité, collecteur d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Collier de serrage, échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Joint d'étanchéité, tuyau d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Bague d'étanchéité, tuyau d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Tuyau flexible, échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Echappement","produit"=>"Clapet de gaz d'échappement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Thermostat d'eau","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Radiateur du moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Liquides refroidissement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Durite de radiateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Intercooler, échangeur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Résistance, pulseur d'air habitacle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Pulseur d'air (ventilateur intérieur)","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Radiateur de chauffage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Moteur électrique, pulseur d'air habitacle","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Compresseur, climatisation","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Condensateur, climatisation","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Bouteille deshydratante","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Actionneur de climatisation","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Sonde de température, liquide de refroidissement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces thermiques et Climatisation","produit"=>"Capteur, niveau d'eau de refroidissement","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Jeu de tapis de sol","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Pare-soleil","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Cale de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Capteur, parctronic","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Avertisseur de marche arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Commande, parctronic","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Support, capteur parctronic","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Centrale clignotante","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Relais, Boîtier de préchauffage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Assortiment d'ampoules (coffret)","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Accessoires et Equipements","produit"=>"Bombe dégivrante","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Vérin de hayon, de coffre","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Vérin de capot moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Vérin de hayon","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Ressort pneumatique, capote","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Mécanisme de lève vitre","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Interrupteur, lève vitre","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Moteur électrique, lève vitre","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Bouchon, réservoir de carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Serrure de porte","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Poignée de porte","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Cylindre de serrure","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Elément d'ajustage, verrouillage central","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Commutateur de colonne de direction","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Interrupteur de commande, régulateur de vitesse","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Comodo d'éclairage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Interrupteur d'essuie glace","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Revêtement de la pédale, pédale d'embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Interrupteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Connecteur de cables","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Fusible","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Porte fusibles","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Ressort tournant, Airbag","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Cale porte","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Guidage à galets, porte coullissante","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Capteur, qualité de l'air","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Avertisseur sonore klaxon","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Joint d'étanchéité de porte","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Joint d'étanchéité, pare brise","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pièces Habitacle","produit"=>"Joint d'étanchéité, vitre arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pneus et Equipements Roue","produit"=>"Enjoliveur, roues","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pneus et Equipements Roue","produit"=>"Boullon de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Pneus et Equipements Roue","produit"=>"Capteur de roue, système de contrôle de pression des pneus","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Additif au carburant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Nettoyant pour moteurs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Additif,  Regénération du filtre à particules/à suie","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Nettoyant pour freins/embrayage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Pâte à joints","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Kit de réparation, palpeur des roues","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Antigel","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Soupape d'injection","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Huile pour transmission automatique","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Entretien et Nettoyage","produit"=>"Brosse métallique, nettoyage de l'étrier de frein","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Attelage et Portage","produit"=>"Dispositif d'attelage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Attelage et Portage","produit"=>"Faisceau d'attelage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Adaptateur, prise","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Support, pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Enjoliveur, pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Kit de montage, choc avant","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Baguette et bande protectrice pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Kit d'assemblage, pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Capuchon, crochet de remorquage","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Support de lampe, feu arrière","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Kit d'assemblage, portes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Baguettes et bande protectrice, porte","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Marche pied","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Fixation de phare","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Grille de pare chocs","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Support projecteur principal","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Cadre, grille de radiateur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Enjoliveur, projecteur antibrouillard","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Ailes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Kit de montage, ailes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Elargissement, ailes","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Passage de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Garniture, passage de roue","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Capot moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Kit d'assemblage, capot moteur","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Carrosserie et Peinture","produit"=>"Cadre de pare brise","prix1"=>1478,"qte"=>0]);
\App\Models\Produit::create(["categorie"=>"Outillages","produit"=>"Outillage divers et coffrets","prix1"=>1478,"qte"=>0]);